### ISSUE TITLE
is anybody using this class?

### ISSUE THREAD

**Issue by miket3** [evopix-archive/orm-mptt#11]
So far the only 3 functions that work are fulltree() rebuild_tree() and delete(). i have had to rewrite anything else i have tried to use.

**Comment by evopix** [comment]
Thats strange. I'm using it in a current app I am building and haven't noticed any issues. I'm thinking [this commit](http://github.com/evopix/orm-mptt/commit/b11c1c0eced51dcb343a871ce2b031e27033ce6b) may be the problem.

**Comment by KRTac** [comment]
I too am using it so far without any problems. Only clear() didn't work properly the last time I tried it (and that was at least 3 weeks ago).

**Comment by evopix** [comment]
Fixed incorrect reference to parent_column. Closed by 17a512435e919fd915cd7a7c7f23573f5ae790e4.
