### ISSUE TITLE
Infinite recursion while trying to make new root

### ISSUE THREAD

**Issue by Alexis2004** [evopix-archive/orm-mptt#16]
I'm trying to create a new root node with new scope using `insert_as_new_root()` method (https://github.com/evopix/orm-mptt/wiki/Usage-Examples example)

But this method is not exist and I replaced it by old `make_root()` method.

While executing script fails with out of memory exception caused infinite recursion.
    make_root() -> save() -> create() -> make_root()

I temporarily fixed it by commenting `create()` method in `Kohana_ORM_MPTT` but don't know is it completely right solution.

**Comment by evopix** [comment]
That's probably the best solution. It's just a convenience method, but because of the changes to ORM in 3.1 it looks like it won't work.

**Comment by evopix** [comment]
Closed by fd186ae2572e33db5840fb3081a704a4debbd27a. Infinite recursion while trying to make new root.
