### ISSUE TITLE
Where I must put this config?

### ISSUE THREAD

**Issue by exvion** [evopix-archive/orm-mptt#19]
Which file?
Config

return array
(
    'left_column' => 'lft',
    'right_column' => 'rgt',
    'level_column' => 'lvl',
    'scope_column' => 'scope',
    'parent_column' => 'parent_id'
);

**Comment by evopix** [comment]
You actually don't need that config anymore. That documentation is outdated. Currently, if you want to change the column names you must do it inside the models declaration.

Like so:

```
class Model_MPTT extends ORM_MPTT {
    public $left_column = 'lft';
    public $right_column = 'rgt';
    public $level_column = 'lvl';
    public $scope_column = 'scope';
    public $parent_column = 'parent_id';
}
```
