### ISSUE TITLE
Speedup the is_parent/sibling/child function with one less database call

### ISSUE THREAD

**Issue by meghuizen** [evopix-archive/orm-mptt#7]
You make use of the $parent_column in your ORM class. But the functions: 
 is_parent/sibling/child use $this->parent and $target->parent, which makes database calls. You can however use $this->{$this->parent_column} als parent id matching, so you dont have to make those database calls anymore.

**Comment by evopix** [comment]
Closed by c94e9a8b3fa5adb0aa49d3c1fe5bcea05eae99c3. Speedup the is_parent/sibling/child function with one less database call,
