### ISSUE TITLE
you make use of id and parent_id while ignoring the variables $parent_column and pk()

### ISSUE THREAD

**Issue by meghuizen** [evopix-archive/orm-mptt#8]
There are some occurences of parent_id as hardcoded column use, when you make use of $parent_column. So I suggest to replace all occurences of ->parent_id with ->{$this->paren_column}

for example in function: parent_from

instead of $col you can also use ->pk() to get the primary key of that object. which is much easier for you.

**Comment by evopix** [comment]
Removing the $col param completely would break the insert_as_prev_sibling, insert_as_next_sibling, move_to_prev_sibling, and move_to_next_sibling methods.

The hardcoded parent_id's do need to be fixed though, and the parent_from method should default to using ->pk(). Thanks.

**Comment by evopix** [comment]
Closed by b11c1c0eced51dcb343a871ce2b031e27033ce6b. you make use of id and parent_id while ignoring the variables $parent_column and pk().
