### ISSUE TITLE
delete function removes all scopes smaller or equal to own scope

### ISSUE THREAD

**Issue by meghuizen** [evopix-archive/orm-mptt#9]
Is this line correct in the delete function:
->where($this->scope_column,' <= ',$this->scope())

I mean the <= of that. Because I suspect that it should be = and not <=.

If this is correct behaviour then I have a wrong understanding of scope. Can you then please tell me what scope is all about and when it's used? If i'm right on this, it's not needed, because I think I do understand.

**Comment by evopix** [comment]
Closed by 121f0d21a3a8e65ca2e7b94071457d5ca3f0ae6a. Delete function removes all scopes smaller or equal to own scope.
